// <auto-generated />
namespace RssDialogys.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02));
        
        string IMigrationMetadata.Id
        {
            get { return "201409302225193_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
